/* Generated By:JavaCC: Do not edit this line. RobotConstants.java */
package uniandes.lym.robot.control;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RobotConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DIGITO = 5;
  /** RegularExpression Id. */
  int CARACTER = 6;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<DIGITO>",
    "<CARACTER>",
    "\"exec\"",
    "\"new\"",
    "\"var\"",
    "\"=\"",
    "\"macro\"",
    "\"(\"",
    "\")\"",
    "\"size\"",
    "\"myx\"",
    "\"myy\"",
    "\"mychips\"",
    "\"myballoons\"",
    "\"balloonshere\"",
    "\"chipshere\"",
    "\"roomforchips\"",
    "\",\"",
    "\"{\"",
    "\";\"",
    "\"}\"",
    "\"nop\"",
    "\"move\"",
    "\"right\"",
    "\"put\"",
    "\"pick\"",
    "\"pop\"",
    "\"hop\"",
    "\"go\"",
    "\"chips\"",
    "\"balloons\"",
    "\"turntomy\"",
    "\"left\"",
    "\"back\"",
    "\"turntothe\"",
    "\"north\"",
    "\"south\"",
    "\"east\"",
    "\"west\"",
    "\"walk\"",
    "\"jump\"",
    "\"drop\"",
    "\"grab\"",
    "\"letgo\"",
    "\"moves\"",
    "\"forward\"",
    "\"backwards\"",
    "\"safeexe\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"fi\"",
    "\"do\"",
    "\"od\"",
    "\"rep\"",
    "\"times\"",
    "\"per\"",
    "\"isblocked?\"",
    "\"front\"",
    "\"isfacing?\"",
    "\"zero?\"",
    "\"not\"",
  };

}
